Test case of possible list issue on mutable API
$ npm test test/list_debug.js

First test passes but second fails with error:

    TypeError: Missing index entry for list element <uuid>:3